# Site settings
title: 菊长的菊花田
description: "新菊花田 ..."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://aicdg.com" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: AICDG
user_title: AICDG - Game Engine Engineer
email: 1156587053@qq.com
twitter_username: 
github_username:  THISISAGOODNAME
gplus_username:  
linkedin_public_url: 245399100 # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: aicdg
profile_picture: http://aicdg.com/oldblog/images/chrysanthemum.jpg
favicon: http://aicdg.com/oldblog/images/chrysanthemum.ico

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: http://aicdg.com/
      key_trigger: 1
    - title: my posts
      url: http://aicdg.com/posts
      key_trigger: 2
    - title: categories
      url: http://aicdg.com/series
      key_trigger: 3
    - title: tags
      url: http://aicdg.com/tags
      key_trigger: 4
    - title: about me
      url: http://aicdg.com/about
      key_trigger: 5
  section_2:
    - title: github
      url: https://github.com/THISISAGOODNAME
      new_tab: true
      key_trigger: g
    - title: old blog
      url: http://aicdg.com/oldblog
      new_tab: true
      key_trigger: o
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"
  section_3:
    - title: blogroll
      url: http://aicdg.com/blogroll
      key_trigger: f
    - title: He-tao's blog
      url: http://sighingnow.github.io
      new_tab: true
      key_trigger: H
    - title: Mictus's website
      url: http://blog.mottomo.moe/
      new_tab: true
      key_trigger: C
    - title: Rainbow's blog
      url: http://kkrainbow.github.io/
      new_tab: true
      key_trigger: K

# projects in header index
projects:
  - name: learn-ammojs
    url: https://github.com/THISISAGOODNAME/learn-ammojs

# blogroll info
blogrolls:
  - name: he-tao
    href: http://sighingnow.github.io
    title: He-tao's blog
  - name: micstu
    href: http://uiharu.moe/
    title: Mictus's website 
  - name: kkrainbow
    href: http://kkrainbow.github.io/
    title: Rainbow's blog   

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
